### ISSUE TITLE
Does this script uses ADFS method to spray ADF services or just BasicAuth method?

### ISSUE THREAD

**Issue by ghost** [ricardojoserf/adfsbrute#1]
Hi, can you please tell me does this script uses ADFS method to spray ADF services or just BasicAuth method ?
Thanks

**Comment by ricardojoserf** [comment]
Hi @Bradli99 ! It aims to mimic the web requests you could send for example from a web browser and you could automate with a proxy such as Burp. So I suppose it could be considered the second option (sorry if I am wrong, I am not an expert in this hahaha)

**Comment by ghost** [comment]
Alright, thanks
