### ISSUE TITLE
what that mean??

### ISSUE THREAD

**Issue by devil67** [ricardojoserf/adfsbrute#2]
Error. Organization probably does not use Office 365.
[-] Response from login.microsoftonline.com:
{
    "IsMicrosoftAccountSet": true,
    "Login": "test@ristoranteilposto.it",
    "MicrosoftAccount": 1,
    "NameSpaceType": "Unknown",
    "cloud_instance_name": "microsoftonline.com"

**Comment by ricardojoserf** [comment]
Hello @devil67 . The first thing this script does is checking if the domain to attack uses a custom ADFS sign-in page or if at least the domain is managed by Microsoft. In this case the domain ("ristoranteilposto.it") does not use Office 365 or, in other words, it is not managed by Microsoft. I hope this explains the output of the command, if not let me know :)
